/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChordDraw: typeof import('./src/components/ChordDraw.vue')['default']
    ChordSelect: typeof import('./src/components/ChordSelect.vue')['default']
    Fingering: typeof import('./src/components/Fingering.vue')['default']
  }
}
